import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { StyledComponentsRegistry } from "./components/StyledComponentsRegistry";

const spoqaHanSansNeo = localFont({
  src: [
    {
      path: "./assets/fonts/SpoqaHanSansNeo/SpoqaHanSansNeo-Thin.woff2",
      weight: "100",
      style: "normal",
    },
    {
      path: "./assets/fonts/SpoqaHanSansNeo/SpoqaHanSansNeo-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "./assets/fonts/SpoqaHanSansNeo/SpoqaHanSansNeo-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./assets/fonts/SpoqaHanSansNeo/SpoqaHanSansNeo-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "./assets/fonts/SpoqaHanSansNeo/SpoqaHanSansNeo-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StyledComponentsRegistry>
      <html lang="ko">
        <body className={spoqaHanSansNeo.className}>{children}</body>
      </html>
    </StyledComponentsRegistry>
  );
}
